### PR TITLE
Update to v2

### PR DESCRIPTION
**Pull request by jaimergp**
xref https://github.com/conda-forge/menuinst-feedstock/pull/23
xref https://github.com/conda/menuinst/releases/tag/2.0.0

### CODE REVIEW

**Comment by JeanChristopheMorinPerso** [comment]
I'll close and re-open to see if we can get the CI to be triggered.

**Comment by JeanChristopheMorinPerso** [comment]
Umm nope, it didn't work. I guess our system prevents people outside Anaconda from trigerring our CI. I'll check with our people to see what could be done.

**Comment by JeanChristopheMorinPerso** [comment]
Alright, so CI can't run if the source is coming from a fork. @jaimergp I'll create a branch and will cherry-pick you commits and I'lll create a new PR.

**Comment by jaimergp** [comment]
Thanks @JeanChristopheMorinPerso!

**Comment by JeanChristopheMorinPerso** [comment]
See https://github.com/AnacondaRecipes/menuinst-feedstock/pull/7

**Pull request closed without merging**
