### PR TITLE
Updating to 1.4.19

### PR DESCRIPTION
**Pull request by ryanskeith**

### CODE REVIEW

**Review by cbouss — COMMENTED** [review]
LGTM, however you can remove the dependency on pywin32:

https://github.com/conda/menuinst/compare/1.4.18...1.4.19#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L19

**Comment by ryanskeith** [comment]
Ah, indeed, we can.  I will remove and hope it passes all builds.

**Comment by skupriienko** [comment]
We can remove m2-patch from build as we do not apply patches

**Review by skupriienko — APPROVED** [review]
Otherwise, LGTM

**Pull request merged**
